export const projects = [
  {
    title: 'OS161',
    description: "Implemented key aspects of the OS161 Operating System in C to be used on the System/161 Hardware Simulator. Programmed the critical constituents of the OS such as mutex locks, threads, processes, file system calls, memory allocation.",
      image: '/images/os161pic.png',
      tags: ['C', 'MIPS', 'GDB', 'Git'],
    source: 'https://github.com/harshil-patel11/CPEN331-OS161',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'CHAT WEB APP',
    description:"Built a responsive web application from scratch that allows users to create chatrooms and chat with their peers or professors. Wrote code for the GUI, client side (frontend), and server side (backend) with tools such as HTML/CSS/JavaScript and Node Js.",
    image: '/images/chatapp-pic.png',
    tags: ['HTML', 'CSS', 'JavaScript', 'MongoDB'],
    source: 'https://github.com/harshil-patel11/cpen322-ChatApp.git',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'RC4 DECRYPTION CIRCUIT',
    description: "Wrote SystemVerilog code for and sythesized a circuit that emulates decryption techniques used by the RC4 stream cipher. Deployed it for use on Intel's DE1-SOC FPGA. Worked with on chip RAM/ROM and Finite State Machines [FSMs] with the start-stop protocol.",
      image: '/images/rc4-pic.png',
      tags: ['SystemVerilog', 'Quartus', 'ModelSim'],
    source: 'https://github.com/harshil-patel11/CPEN311-Labs/tree/master/RC4-Decryptor',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'PS4 GAME RECOMMENDER',
    description: "Developed an app on Android Studio using Machine Learning techniques to recommend PS4 games based on user game tastes, likes and input images. Designed a user-friendly app interface with Android Studio and set up a Node Js HTTP server to handle user requests.",
    image: '/images/ps4-pic.png',
    tags: ['Android Studio', 'Python/Pytorch', 'Node Js', 'Google Colab'],
    source: 'https://github.com/UBC-CPEN291/project-team-spinosaurus.git',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'RISC MICROCONTROLLER',
    description: "Assembled a simple RISC CPU and deployed it for use on Intel's DE1-SOC FPGA. Wrote code for critical components of the CPU such as multiplexers, decoders, encoders, registers",
    image: '/images/risc-pic.png',
    tags: ['Verilog', 'Quartus', 'ModelSim'],
    source: 'https://github.com/harshil-patel11/RISC-Microcontroller.git',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'PERSONAL WEBSITE',
    description: "This is the code repository for this  personal portfolio website. It was built using Next Js and React Js and can be deployed following the steps from the README on GitHub.",
    image: '/images/portfolio-pic.png',
    tags: ['React', 'Next', 'JavaScript'],
    source: 'https://github.com/harshil-patel11/personal-portfolio-website.git',
    visit: 'https://google.com',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2019, text: 'Started my coding journey at UBC', },
  { year: 2020, text: 'Made projects with C, C++, Java, and Verilog/SystemVerilog', },
  { year: 2021, text: 'Made my first few web apps / ML applications', },
  { year: 2022, text: 'Looking for first job opportunity', },
];